import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import AuthSesionProvider from "./context/authSesionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fund Me",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthSesionProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </AuthSesionProvider>
    </html>
  );
}
